### ISSUE TITLE
Poor Results on Jetson Nano

### ISSUE THREAD

**Issue by justvasq** [zerollzeng/tensorrt-zoo#31]
Hello,

I followed the general instructions + Jetson Nano suggestions from #25 and the resulting image did not look great:

![result](https://user-images.githubusercontent.com/63258842/94856282-9a3c4500-03e4-11eb-9974-2e6da34ee4ca.jpg)

Any idea as to what could cause this result? Thanks

**Comment by zerollzeng** [comment]
Sorry for the late reply, I'm on vacation these days, could you provide more details about your issue？ eg, cmake output and running output.
PS. tensorrt-zoo and tiny-tensorrt was develop under x86 linux, I don't have jetson device for test sry~

**Comment by liuwei0812** [comment]
in you   jetson nano a img  use  hao  long  time ? in my  jetson nano use 1.5s a img(640*480)
  it's so  slow.
for your question , I use 640*480 works right ,but when I use  320*240 ,my result   body point is  not on  person like you,  after modify prototxt  and testopenpose.cpp  It works right.
in  openpose.md write:modify prototxt's inputdims to 1x3x480x640 for run test sample since tensorrt need a fix input dimemsion. you can use other w and h value too. but make sure it's multiple of 16.

**Comment by zerollzeng** [comment]
> in you jetson nano a img use hao long time ? in my jetson nano use 1.5s a img(640_480)_

sorry I don't have a jetson nano device, all my development is under linux x86 platform 

> _for your question , I use 640_480 works right ,but when I use 320*240 ,my result body point is not on person like you, after modify prototxt and testopenpose.cpp It works right.

yeah it's need some modification on testopenpose.cpp, mainly the H and W.

**Comment by zerollzeng** [comment]
btw openpose is not that kind of light-weight model design for embedded device, so I think it's normal that running slow in your jetson nano.
